spring:
  application:
    name: xdaas-admin
  profiles:
    active: @x.env@
  datasource:
    url: jdbc:mysql://xdaas.cn:3306/xdaas-admin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT-8
    username: root
    password: flowers2020
    type: com.alibaba.druid.pool.DruidDataSource
    #下面这些参数为固定参数,无需修改
    filters: config,wall
    db-type: mysql
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filter:
      stat:
        enabled: false
      wall:
        enabled: true
    web-stat-filter:
      enabled: false
    stat-view-servlet:
      enabled: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
logging:
  config: classpath:config/logback-spring.xml
